version: '3'
services:
  web:
    image: gaston-image
    ports:
      - "8200:8000"
    networks:
      - app_network


  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - ./dbdata:/var/lib/mysql/
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
